version: 2.1

orbs:
  node: circleci/node@5.2.0

jobs:
  # Job to build the project and run tests
  build_and_test:
    machine:
      image: ubuntu-2204:2024.01.1
    steps:
      - checkout
      - node/install:
          node-version: '22.3'
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Run tests
          command: npm test

  # Job to publish a canary version
  publish_canary:
    machine:
      image: ubuntu-2204:2024.01.1
    steps:
      - checkout
      - node/install:
          node-version: '22.3'
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Authenticate with NPM registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run:
          name: Publish canary package
          command: |
            npm publish --tag canary || { echo "npm publish failed, stopping the job."; exit 1; }

  # Job to validate the main version
  validate_main_version:
    machine:
      image: ubuntu-2204:2024.01.1
    steps:
      - checkout
      - run:
          name: Validate version
          command: ./bin/ci_validate_version.sh

  # Job to publish the final package
  publish:
    machine:
      image: ubuntu-2204:2024.01.1
      resource_class: large
    steps:
      - checkout
      - node/install:
          node-version: '22.3'
      - run:
          name: Authenticate with NPM registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Publish package
          command: npm publish

workflows:
  CI:
    jobs:
      - build_and_test
      - require_approval_for_canary:
          type: approval
          filters:
            branches:
              only:
                - dev
      - publish_canary:
          requires:
            - build_and_test
            - require_approval_for_canary
          filters:
            branches:
              only:
                - dev
      - validate_main_version:
          requires:
            - build_and_test
          filters:
            branches:
              only:
                - main
      - require_approval:
          type: approval
          filters:
            branches:
              only:
                - main
      - publish:
          requires:
            - build_and_test
            - require_approval
            - validate_main_version
          filters:
            tags:
              only: /.*/
            branches:
              only:
                - main
